M48
; DRILL file {KiCad 8.0.5} date 2025-02-13T10:20:43+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-02-13T10:20:43+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X185.445Y-101.295
T2
X180.52Y-72.895
X189.52Y-72.895
T3
X144.445Y-61.395
X144.445Y-115.395
X188.445Y-61.395
X188.445Y-115.395
M30
